
// "use client";
import { ColorPaletteComponent } from "@/component/color-pallete-component";
import { Metadata } from "next/types";

export default function App() {


  return <div><ColorPaletteComponent />
  ini adalah warna dasar dengan hex color
  </div>
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
